#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."
alias code='cd ~/code; pwd; ls'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim --"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias q="exit"
alias rm="rm -rf --"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias gs='git status '
alias gc='git commit '
alias gl='git log'
alias lsr='ls -R'
alias lss='ls -la@'


# ----------------------------------------------------------------------
# | Silly                                                              |
# ----------------------------------------------------------------------
alias bosskey='cat /dev/urandom | hexdump -C | grep "ca fe"'

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
